### ISSUE TITLE
lines getting cropped too fast 

### ISSUE THREAD

**Issue by 3blackbar** [new-sankaku/stable-diffusion-webui-simple-manga-maker#12]
heres cropping issue, i think instead of autocrop you should really create A4 templates for manga A5 maybe so its not a square and we can place our frames properly when the space resembles a page with its aspect ratio, but please fix the cropping anyways, it has issues sometimes keeping the black borders / lines of the frames/panels 
![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/162857724/97b6bdf9-5588-4a16-9e9f-2f4dc275161a)

**Comment by new-sankaku** [comment]
thank you. I'll check it out.

**Comment by 3blackbar** [comment]
ITs strange, sometimes it crops nicely and the issue is not happening, so, not sure how to reproduce it, i think it would be just best to keep the whole page same aspec ration as manga page and dont autocrop at all
This one has nice black borders  
![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/162857724/50225762-b7c8-4a6f-a4c5-4f589e5390c0)

**Comment by new-sankaku** [comment]
thank you!
This may be a bug in Fabric.js, but there is a problem where the display area is destroyed when performing REDO and UNDO processing.

As you said, you can confirm that the display area at the bottom of the panel is destroyed by the following operation. Select a Panel, drop images on all Panels, and perform UNDO.

We are working on this as a priority, but there is no clear plan at this point. Maybe I'll add custom REDO and UNDO.

**Comment by new-sankaku** [comment]
This has been fixed in the latest version. By default, Fabric.js did not provide complete precision information, and certain parts below the decimal point were truncated.

However, there are the following restrictions.
Click Panel to select it, then Undo. The line width becomes thinner and a margin is created when dropping the image. Therefore, we have added a restriction so that Undo cannot be performed when a new Panel is selected.

Please note that there is no problem with the following operations.
Click Panel to select it, drop the image, then Undo. In this state it is fully operational.
