### ISSUE TITLE
Project Save - Does not maintain image resize/position.

### ISSUE THREAD

**Issue by 0m3ga4** [new-sankaku/stable-diffusion-webui-simple-manga-maker#18]
After resizing an image inside a panel, saving a project, and then loading the project, the image will reset to its default position.

**Comment by new-sankaku** [comment]
Fixed a similar issue.
A similar issue was reproduced using the following steps.
1.Add Panel
2. Add multiple images
3. Change the size of your web browser
4. Execute Undo

Because the Canvas size added in 2 and the Canvas size when executing 4 were different, it is displayed in a reduced size.

I will wait for this issue to be reproduced.
