### ISSUE TITLE
Aspect Ratio for Panels [Idea]

### ISSUE THREAD

**Issue by LindezaBlue** [new-sankaku/stable-diffusion-webui-simple-manga-maker#31]
Something I think would really help for standardized posts to social media _(like Instagram)_ would be resizable panels to an exact aspect ratio like **3:4, 2:3** etc.

**Example:**
![4x3 Template](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/141217866/fc60facc-0687-4952-8236-4e0132adbf17)

One of the things I have a difficult time is making sure each panel is the exact dimensions for uploading single panels to Instagram's 4:3 aspect ratio. I still want to have all the images on one page _(four 4:3 panels for my case)_ but after I save my image with the four panels, I usually crop each panel out so I can upload each panel so it can be swiped from right to left.

Example Post:
https://www.instagram.com/p/C8kJJG3py5P/?img_index=1

And for the last post I upload the 4 panels all together as a normal comic panel.

I think having the ability to set a size to each panel would really help with this.

**Comment by new-sankaku** [comment]
I understand.
I will add some features.
Please confirm if this aligns with what you want to achieve.

I will add an aspect ratio setting for adding squares, rectangles, and trapezoids. I will leave other shapes as they are.

I will also add some page presets with different ratios. A4-like ones, 4:5, 1:1, 1.91:1, etc. I think I will add a separate sidebar.

I will also add a download button to the panel layer. I will make it possible to download the panel area as an image.

I will add a size change button to the panel layer, so that the aspect ratio can be changed. I am not sure if I will be able to specify pixels.

However, I am busy with work and may not be able to release it immediately. Therefore, it may be released in stages.

**Comment by LindezaBlue** [comment]
> I understand. I will add some features. Please confirm if this aligns with what you want to achieve.
> 
> I will add an aspect ratio setting for adding squares, rectangles, and trapezoids. I will leave other shapes as they are.
> 
> I will also add some page presets with different ratios. A4-like ones, 4:5, 1:1, 1.91:1, etc. I think I will add a separate sidebar.
> 
> I will also add a download button to the panel layer. I will make it possible to download the panel area as an image.
> 
> I will add a size change button to the panel layer, so that the aspect ratio can be changed. I am not sure if I will be able to specify pixels.
> 
> However, I am busy with work and may not be able to release it immediately. Therefore, it may be released in stages.

Sounds good so far, it's not urgent so please don't feel rushed. Everyone has lives, please take your time. Once a feature comes out, I'll run some tests and give feedback.

Thank you for for considering the idea. 😁👍🏼

**Comment by new-sankaku** [comment]
![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/133557155/4a726848-0476-4878-8dfb-c67fb01e2c79)

![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/133557155/3c08c911-754b-43ad-b35f-8a826b8b121f)


I've added a process to create page presets and
Accept Ratio Rects.
Please note that the sidebar is now split.

Image cropping will probably be done next week!

**Comment by LindezaBlue** [comment]
So far it looks good. The settings are not live yet within A1111, but I was able to test them in the stand-alone viewer.
I think the aspect ratio's are correct, I will need to do some more testing and see if I run into issues there but the concept looks good so far.

The only thing is when I want to have a full page with _four (4)_ panels set to an aspect ratio of **4:5** _(Instagram's portrait size)_ There is no way for me to align the small panels in a 2x2 grid. _(4 panels in total on a single page.)_

**A single 4:5 square pictured below:**
![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/141217866/ed33fbe9-32c6-411b-b7cf-3ab37a6dd118)
That square is quite small as well.

_______________________________________

**Ideally it should like like this:**
![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/141217866/fa7f2761-a448-42ef-b506-e1b1ee1fe18e)

Having some button to align squares next to each other so that it looks like the above example would really help with panel placement when working with multiple panels with the same size.

**Comment by new-sankaku** [comment]
Thanks for confirming!

If you want to align using the current function, the following steps should be useful.

Turn on the Grid display using Ctrl + G or from the Canvas menu, select a Panel and press the D-pad to move the Object according to the Grid width. This allows you to align the Panel on the X/Y axis. I'm sure it should also move while fitting to the grid size when dragged with the mouse...

If I were to implement an alignment function for Panels, it would take a long time to implement because it would affect other Objects. It might be easier to just add a 2*2 Panel to the preset.

**Comment by LindezaBlue** [comment]
Everything looks good so far. 
The only thing I would like to see if it's possible is this panel but for vertical orientation:
![image](https://github.com/user-attachments/assets/2c722e70-ee0d-413d-86b6-91bfeb4028d0)

It is already implemented in the horizontal panel section but not the vertical section.
![image](https://github.com/user-attachments/assets/d30b5464-6a64-4358-9510-cc5c3000f25a)
Adding that to the vertical panels would round out the selection a bit better.

**Comment by LindezaBlue** [comment]
I see it was added to the extension, I really appreciate the added features. I think everything I've tested so far works really well. Haven't found any issues with it.

**Comment by new-sankaku** [comment]
Sorry, I added it yesterday but I was sleepy so I just went to sleep. I'm glad it worked!

**Comment by LindezaBlue** [comment]
> Sorry, I added it yesterday but I was sleepy so I just went to sleep. I'm glad it worked!

Hey no worries, I hope you are not overworking yourself. Thank you so much for all your hard work!~
