### ISSUE TITLE
add some controls buttons to move image up/down.left.right and scale control 

### ISSUE THREAD

**Issue by 3blackbar** [new-sankaku/stable-diffusion-webui-simple-manga-maker#7]
Also it takes awhile to process every image and its just a simple layering and drag dropping of images so...  its needs a lot of additions to be acceptable ,theres many of those online so you can just drag and drop an image and position it in realtime.
Without realtime operations on each layer its very very crude and slow.
You also cant go back to previous layer to change it...  i dont think this is release ready really.

**Comment by new-sankaku** [comment]
I understand what you're saying. There is a need to add some features, but I do not intend to implement advanced operations.

As you have mentioned, there are other image editing sites and software available. However, I'm not aiming to create a product that replaces these, so I don't plan to implement the same level of functionality.

What I'm aiming for is to enable casual editing of images without the need for a learning curve. Therefore, I'm keeping operations as simple as clicking buttons.

If you need layer management or real-time editing, for example, there is MiniPaint which can extend SD Webui, among other sites.
https://github.com/0Tick/a1111-mini-paint.git

I hope you can understand this is a matter of concept. However, I do recognize that there are some features we should add.

By the way, how long do you find the processing to be heavy? In my environment, it takes about 2-3 seconds per panel. I am aware that the size of the panels we're providing can lead to longer processing times, but since we're assuming the use of a GPU, I didn't particularly worry it would be too slow.

**Comment by 3blackbar** [comment]
Thats ok, i built it today for myself with python game so i can add images one by one and pace them however i want on canvas , gradio is a bit limited with realtime feedback and graphic operations .
Im on 3090 and simply applying chosen image as image1 ,2 or 3 takes way too long, like 3 seconds so something must be off, this should be lighting fast even on cpu, no gpu should be needed.
I built a canvas whre i can scale ,rotate and move xy image using keyboard shortcuts, here in this extension i would add buttons for changing scale,rotation and xy position of each imported image but this needs realtime feedback when you adjust it.So when you scale image it autoupdates it  in comic panel.
Also it needs ability to go back to any image at any time to adjust scaling ,rotation etc ... 
If it cant have it cause of gradio then imo its not worth your time.
I had photopea extension but didnt used it much, i prefere to copy paste clipboard form gimp ,im used to it.

**Comment by new-sankaku** [comment]
Thank you for the suggestion. I understand your concerns.

Indeed, I hadn't paid much attention to it, but you're right that the process of pasting images does take seconds. This could be due to the file size or the fact that we're applying masks to specific frames, which might be causing issues. I do want to improve usability, but it might be a lower priority for now.

As for reverting image changes, you can use the "Revert Changes" button, but does this meet your needs? I'm not a native English speaker, so if the button's name is unclear, I'm willing to change it.

Regarding scale changes, we intended to use the ImageEditor component that comes with Gradio's Version 4. However, I saw that there's been a PR for SD Web UI that requires Gradio 4, but the conversation has stalled for the last two weeks.

Also, it was possible to specify tool="select" in the Image component, but it turned out to be impractical for use due to poor operability.

I'm currently at work, so I'll take a closer look at your suggestions when I have some time.

**Comment by new-sankaku** [comment]
I fixed it quite a bit (or rather, it became a different thing)

**Comment by new-sankaku** [comment]
I'll close it for now, so if you have any other problems, please raise them in Issues.

**Comment by 3blackbar** [comment]
wow. this is the same extension man ? You did amazing job i must say compared to first version.

**Comment by new-sankaku** [comment]
The first version was stuck in improving performance. 
(´・ω・`)

Therefore, we separated it from Stable diffusion WebUI and rewrote the code based on Html, Css, and JavaScript.

**Comment by 3blackbar** [comment]
Well its now pretty much perfect, i didnt expect that much of an improvement ,great job
