### ISSUE TITLE
[BUG] stable diffusion missing scroll bars after update

### ISSUE THREAD

**Issue by BrianStark** [new-sankaku/stable-diffusion-webui-simple-manga-maker#9]
Hi there,

After yesterday's update, the right vertical scroll bar is missing on every stable divusion tab. This only happens if I enable this extension.
so unfortunately for now I'm leaving this extension off otherwise I won't be able to use the program for anything else.

I hope this problem can be fixed soon.

**Comment by prezofpizza** [comment]
Confirming I ran into the same issue using Forge.

**Comment by new-sankaku** [comment]
Hi there,

We have identified the issue you mentioned where the right vertical scroll bar goes missing on every stable division tab after enabling our extension. This was caused by an unintended replacement process in our Python code, and we deeply apologize for any inconvenience it may have caused.

We have corrected this issue in the latest update. Please update the extension to the newest version to resolve this problem.

Thank you for your patience, and we're sorry for the inconvenience. We hope this fix will improve your experience using our program.
